Adds missing parameters for ConnectWebview creation
seamapi/ruby-legacy pull request #52
Opened 2023-06-09 01:43 UTC by AxelTheGerman

Adds missing parameters from the docs: https://docs.seam.co/latest/api-clients/connect-webviews/create-a-connect-webview#parameters

Might want to add to the Ruby SDK docs as well.

In action:
```
> seam.connect_webviews.create custom_redirect_url: 'http://localhost:3000/success', custom_redirect_failure_url: 'http://localhost:3000/failure', device_selection_mode: 'multiple'
 => 
<Seam::ConnectWebview:0x0039bc0
  url="https://connect.getseam.com/connect_webviews/view?connect_webview_id=d5b63064-1a31-4a92-b9f4-f0b0756d24d7&auth_token=8W1uRbJHhvmWb2VN6SQKz4rfeX7qSJVms"
  status="pending"             
  created_at=2023-06-09 01:26:40.146964 +0000
  workspace_id="073c47ff-c6d8-4f81-ab10-eda14295fbe0"
  accepted_devices=[]          
  login_successful=false       
  accepted_providers=["august", "avigilon_alta", "schlage", "smartthings", "yale", "nuki", "salto", "controlbyweb", "minut", "my_2n", "kwikset", "ttlock", "noiseaware", "igloohome", "ecobee"]
  any_device_allowed=nil       
  connect_webview_id="d5b63064-1a31-4a92-b9f4-f0b0756d24d7"
  custom_redirect_url="http://localhost:3000/success"
  any_provider_allowed=false
  device_selection_mode="multiple"
  custom_redirect_failure_url="http://localhost:3000/failure">
```

2023-06-09 01:46 UTC, AxelTheGerman commented on lib/seam/clients/connect_webviews.rb
> +          }.compact
compact combined with default `nil` for device selection ensures using the correct default as per Seam backend implementatiom

2023-06-09 01:52 UTC, sybohy commented on lib/seam/clients/connect_webviews.rb
> +          }.compact
i didn't know about `compact`. very nifty

2023-06-09 01:55 UTC, sybohy approved these changes, later dismissed

2023-06-09 01:55 UTC, sybohy commented on lib/seam/clients/connect_webviews.rb
> +          }.compact
btw we have `provider_category` that could be passed as well. e.g. `provider_category="stable"` which auto-populates a list of providers that are deemed "stable"

2023-06-09 01:56 UTC, sybohy commented on lib/seam/clients/connect_webviews.rb
> +          }.compact
An example: https://github.com/seamapi/python/pull/97/files
Our team will need to add it to the doc as well.

2023-06-09 13:58 UTC, AxelTheGerman commented on lib/seam/clients/connect_webviews.rb
> +          }.compact
Neat, I remember you mentioned that. I might as well add it in too then

2023-06-09 19:26 UTC, razor-x requested changes
Thank you! Just the one note :)

2023-06-09 19:26 UTC, razor-x commented on lib/seam/clients/connect_webviews.rb
> +        accepted_providers: [],
With the new `provider_category` option, this is now optional as well.

```suggestion
        accepted_providers: nil,
```

2023-06-09 19:44 UTC, AxelTheGerman commented on lib/seam/clients/connect_webviews.rb
> +        accepted_providers: [],
Good call I will have a look. Previously specifying `nil` explicitly was giving me an error - but since I added the `compact` which removes keys for nil values it should probably not be an issue anymore.

2023-06-12 00:26 UTC, AxelTheGerman commented on lib/seam/clients/connect_webviews.rb
> +        accepted_providers: [],
Done! :)

2023-06-12 15:01 UTC, razor-x approved these changes

2023-06-12 15:02 UTC, merged